# Set the name of your application:
APPLICATION = tfmicro_test
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
FEATURES_REQUIRED += cpp
FEATURES_REQUIRED += libstdcpp
USEPKG += tflite-micro

include $(RIOTBASE)/Makefile.include
