# Set the name of your application:
APPLICATION = power_off
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
USEMODULE += shell
DISABLE_MODULE = auto_init

include $(RIOTBASE)/Makefile.include
