# Set the name of your application:
APPLICATION = clear_eeprom
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
USEMODULE += periph_eeprom
DISABLE_MODULE = auto_init

include $(RIOTBASE)/Makefile.include
