# Set the name of your application:
APPLICATION = power_test
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
DISABLE_MODULE = auto_init
USEMODULE += periph_rtc

include $(RIOTBASE)/Makefile.include
