# Set the name of your application:
APPLICATION = test_rtc_mem
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
USEMODULE += periph_rtc periph_rtc_mem

include $(RIOTBASE)/Makefile.include
