# Set the name of your application:
APPLICATION = clear_flash
 
PROJECT_BASE = $(CURDIR)/../../
BOARD ?= b-l072z-lrwan1
RIOTBASE ?= $(PROJECT_BASE)/RIOT
DEVELHELP = 1
USEMODULE += mtd_flashpage

SLOT_AUX_LEN := 0x8000
include $(RIOTBASE)/Makefile.include
